#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mono
Version  : 5.2.0.215
Release  : 2
URL      : https://github.com/mono/mono/archive/mono-5.2.0.215.tar.gz
Source0  : https://github.com/mono/mono/archive/mono-5.2.0.215.tar.gz
Source1  : https://download.mono-project.com/monolite/monolite-1050200001-latest.tar.gz
Source2  : https://github.com/mono/NUnitLite/archive/690603bea98aae69fca9a65130d88591bc6cabee.tar.gz
Source3  : https://github.com/mono/Newtonsoft.Json/archive/471c3e0803a9f40a0acc8aeceb31de6ff93a52c4.tar.gz
Source4  : https://github.com/mono/NuGet.BuildTasks/archive/8d307472ea214f2b59636431f771894dbcba7258.tar.gz
Source5  : https://github.com/mono/api-doc-tools/archive/d03e819838c6241f92f90655cb448cc47c9e8791.tar.gz
Source6  : https://github.com/mono/aspnetwebstack/archive/e77b12e6cc5ed260a98447f609e887337e44e299.tar.gz
Source7  : https://github.com/mono/bockbuild/archive/b445017309aac741a26d8c51bb0636234084bf23.tar.gz
Source8  : https://github.com/mono/boringssl/archive/3e0770e18835714708860ba9fe1af04a932971ff.tar.gz
Source9  : https://github.com/mono/cecil/archive/33d50b874fd527118bc361d83de3d494e8bb55e1.tar.gz
Source10  : https://github.com/mono/cecil/archive/c76ba7b410447fa37093150cb7bc772cba28a0ae.tar.gz
Source11  : https://github.com/mono/corefx/archive/74ccd8aa00d7d271191ca3b9c4f818268dc36c28.tar.gz
Source12  : https://github.com/mono/corert/archive/48dba73801e804e89f00311da99d873f9c550278.tar.gz
Source13  : https://github.com/mono/ikdasm/archive/1d7d43603791e0236b56d076578657bee44fef6b.tar.gz
Source14  : https://github.com/mono/ikvm-fork/archive/847e05fced5c9a41ff0f24f1f9d40d5a8a5772c1.tar.gz
Source15  : https://github.com/mono/linker/archive/21e445c26c69ac3a2e1441befa02d0bd105ff849.tar.gz
Source16  : https://github.com/mono/reference-assemblies/archive/142cbeb62ffabf1dd9c1414d8dd76f93bcbed0c2.tar.gz
Source17  : https://github.com/mono/roslyn-binaries/archive/80b86f340b7f6fb7afe84443214e1cbd7ff70620.tar.gz
Source18  : https://github.com/mono/rx/archive/b29a4b0fda609e0af33ff54ed13652b6ccf0e05e.tar.gz
Source19  : https://github.com/mono/xunit-binaries/archive/d4433b0972f40cb3efaa3fbba52869bde5df8fa8.tar.gz
Summary  : Mono Runtime
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 MIT
BuildRequires : attr-dev
BuildRequires : cmake
BuildRequires : go
BuildRequires : llvm-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(zlib)

%description
* purpose
This tool is to generate globalization information from Unicode CLDR, with some changes
to fill the gap between .NET(Windows)-ism and the global standard.

%prep
tar -xf %{SOURCE1}
tar -xf %{SOURCE8}
tar -xf %{SOURCE3}
tar -xf %{SOURCE5}
tar -xf %{SOURCE6}
tar -xf %{SOURCE16}
tar -xf %{SOURCE7}
tar -xf %{SOURCE10}
tar -xf %{SOURCE9}
tar -xf %{SOURCE11}
tar -xf %{SOURCE12}
tar -xf %{SOURCE13}
tar -xf %{SOURCE14}
tar -xf %{SOURCE15}
tar -xf %{SOURCE4}
tar -xf %{SOURCE2}
tar -xf %{SOURCE17}
tar -xf %{SOURCE18}
tar -xf %{SOURCE19}
cd ..
%setup -q -n mono-mono-5.2.0.215
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/mcs/class/lib/monolite/1050200001/
mv %{_topdir}/BUILD/monolite-1050200001-latest/* %{_topdir}/BUILD/mono-mono-5.2.0.215/mcs/class/lib/monolite/1050200001/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/boringssl/
mv %{_topdir}/BUILD/boringssl-3e0770e18835714708860ba9fe1af04a932971ff/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/boringssl/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/Newtonsoft.Json/
mv %{_topdir}/BUILD/Newtonsoft.Json-471c3e0803a9f40a0acc8aeceb31de6ff93a52c4/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/Newtonsoft.Json/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/api-doc-tools/
mv %{_topdir}/BUILD/api-doc-tools-d03e819838c6241f92f90655cb448cc47c9e8791/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/api-doc-tools/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/aspnetwebstack/
mv %{_topdir}/BUILD/aspnetwebstack-e77b12e6cc5ed260a98447f609e887337e44e299/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/aspnetwebstack/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/binary-reference-assemblies/
mv %{_topdir}/BUILD/reference-assemblies-142cbeb62ffabf1dd9c1414d8dd76f93bcbed0c2/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/binary-reference-assemblies/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/bockbuild/
mv %{_topdir}/BUILD/bockbuild-b445017309aac741a26d8c51bb0636234084bf23/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/bockbuild/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/cecil/
mv %{_topdir}/BUILD/cecil-c76ba7b410447fa37093150cb7bc772cba28a0ae/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/cecil/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/cecil-legacy/
mv %{_topdir}/BUILD/cecil-33d50b874fd527118bc361d83de3d494e8bb55e1/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/cecil-legacy/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/corefx/
mv %{_topdir}/BUILD/corefx-74ccd8aa00d7d271191ca3b9c4f818268dc36c28/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/corefx/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/corert/
mv %{_topdir}/BUILD/corert-48dba73801e804e89f00311da99d873f9c550278/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/corert/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/ikdasm/
mv %{_topdir}/BUILD/ikdasm-1d7d43603791e0236b56d076578657bee44fef6b/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/ikdasm/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/ikvm-fork/
mv %{_topdir}/BUILD/ikvm-fork-847e05fced5c9a41ff0f24f1f9d40d5a8a5772c1/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/ikvm-fork/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/linker/
mv %{_topdir}/BUILD/linker-21e445c26c69ac3a2e1441befa02d0bd105ff849/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/linker/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/nuget-buildtasks/
mv %{_topdir}/BUILD/NuGet.BuildTasks-8d307472ea214f2b59636431f771894dbcba7258/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/nuget-buildtasks/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/nunit-lite/
mv %{_topdir}/BUILD/NUnitLite-690603bea98aae69fca9a65130d88591bc6cabee/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/nunit-lite/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/roslyn-binaries/
mv %{_topdir}/BUILD/roslyn-binaries-80b86f340b7f6fb7afe84443214e1cbd7ff70620/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/roslyn-binaries/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/rx/
mv %{_topdir}/BUILD/rx-b29a4b0fda609e0af33ff54ed13652b6ccf0e05e/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/rx/
mkdir -p %{_topdir}/BUILD/mono-mono-5.2.0.215/external/xunit-binaries/
mv %{_topdir}/BUILD/xunit-binaries-d4433b0972f40cb3efaa3fbba52869bde5df8fa8/* %{_topdir}/BUILD/mono-mono-5.2.0.215/external/xunit-binaries/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1502834576
%autogen --disable-static --with-tls=pthread \
--target=x86_64-generic-linux-gnu \
--enable-static \
--with-static_mono=yes
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1502834576
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
