#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mono
Version  : 5.2.0.213
Release  : 1
URL      : https://github.com/mono/mono/archive/mono-5.2.0.213.tar.gz
Source0  : https://github.com/mono/mono/archive/mono-5.2.0.213.tar.gz
Summary  : Mono Runtime
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 MIT
BuildRequires : attr-dev
BuildRequires : cmake
BuildRequires : llvm-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(zlib)

%description
* purpose
This tool is to generate globalization information from Unicode CLDR, with some changes
to fill the gap between .NET(Windows)-ism and the global standard.

%prep
%setup -q -n mono-mono-5.2.0.213

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1501527835
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1501527835
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
